title: "Real-Time IoT-Enabled Cardiovascular Monitoring System"
description: "Full project report â€” ESP32-based real-time PPG system with custom AFE and IoT."
theme: jekyll-theme-cayman
show_downloads: false
